# Generated by Django 5.2.7 on 2025-10-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_variations_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varaition_value',
            new_name='variation_value',
        ),
    ]
